name: gate-test
on:
  push:
    branches: [staging]
jobs:
  fast:
    uses: web-masters-ke/wasaa-ci/.github/workflows/ci-fast.yml@main
    with:
      stack: typescript
      db: ""
      has_openapi: false
      node_version: '20'
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.WASAA_SEMGREP_APP_TOKEN }}
